# 测试目标注册的唯一入口:统一 GTest 链接、cxx_std_20、用例发现与工作目录。
# 每个测试目录的 CMakeLists 只需一条 realm_add_gtest 调用。
#
#   realm_add_gtest(<name>
#       SOURCES <src> ...
#       [LIBS <lib> ...]
#       [INCLUDE_DIRS <dir> ...]
#       [DEFINITIONS <K=V> ...]
#       [DEPENDS <target> ...]
#       [LABELS <label> ...]                        # 缺省 unit;约定见下
#       [DISCOVER_PROPERTIES <prop> <value> ...]   # 例如 RUN_SERIAL TRUE
#   )
#
# 标签约定(ctest -L 依赖它划分快速子集与全量):unit = 进程内 GTest,
# 不拉子进程、不占固定端口;integration = 驱动真实二进制/真实端口或跨进程
# (e2e、bash 脚本、RUN_SERIAL 性质)。分类标签只有这两个,每次注册恰好带
# 其一(否则配置失败);Lua 套件(realm_add_lua_test)在 unit 之外另带 lua 标签。
# 新增测试必须带标签:常规 GTest 用缺省即可,占用固定端口或拉起
# realm_mesh 的目标必须显式 LABELS integration,否则会混进快速子集里抢端口。
# 快速子集走 ./scripts/test-fast.sh,全量走 ./scripts/build.sh。
#
# 注册同时生成两样东西(#125),不另维护手写清单:
# - Unit 聚合目标 realmmesh_unit_tests:依赖每个 Unit 构建目标(Lua 套件则是
#   realm_lua_cli),test-fast.sh 只构建它而不是 ALL;
# - 精确目标身份标签 target=<构建目标>:与分类标签一起作为一个列表值挂到
#   该目标的每个用例上。标签是子串匹配的正则,手工筛选要写锚点,例如
#   ctest -L '^unit$'、ctest -L '^target=lua_runtime_test$'。
# 根 CMakeLists 在所有测试目录之后调用 realmmesh_write_unit_test_registry(),
# 把 Unit 构建目标及其产物路径写进 <构建目录>/realmmesh-unit-targets.txt。
#
# 用例的工作目录固定在 tests/cpp 构建目录(REALMMESH_TEST_WORKING_DIRECTORY)。
# 拆分前该目录是 gtest_discover_tests 的隐式默认值;现在显式传入,避免依赖
# add_subdirectory 的默认值变化导致测试的相对路径语义漂移。

include(GoogleTest)

if(NOT TARGET realmmesh_unit_tests)
    add_custom_target(realmmesh_unit_tests)
endif()

# 分类标签恰好是 unit / integration 之一;返回值 <out_class> 为 unit 或 integration。
function(_realm_test_classification out_class labels)
    set(classes "")
    foreach(label IN LISTS labels)
        if(label STREQUAL "unit" OR label STREQUAL "integration")
            list(APPEND classes "${label}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES classes)
    list(LENGTH classes class_count)
    if(NOT class_count EQUAL 1)
        message(FATAL_ERROR
            "Test labels \"${labels}\" must carry exactly one of unit / integration "
            "(see tests/cmake/test_helpers.cmake).")
    endif()
    set(${out_class} "${classes}" PARENT_SCOPE)
endfunction()

# 把 Unit 构建目标并入聚合目标与登记清单(重复登记只记一次)。
function(_realm_register_unit_target target)
    get_property(registered GLOBAL PROPERTY REALMMESH_UNIT_TARGETS)
    if(NOT target IN_LIST registered)
        set_property(GLOBAL APPEND PROPERTY REALMMESH_UNIT_TARGETS "${target}")
        add_dependencies(realmmesh_unit_tests "${target}")
    endif()
endfunction()

function(realm_add_gtest name)
    cmake_parse_arguments(PARSE_ARGV 1 ARG ""
        ""
        "SOURCES;LIBS;INCLUDE_DIRS;DEFINITIONS;DEPENDS;LABELS;DISCOVER_PROPERTIES")

    if(NOT ARG_LABELS)
        set(ARG_LABELS unit)
    endif()
    _realm_test_classification(test_class "${ARG_LABELS}")

    add_executable(${name} ${ARG_SOURCES})
    # 测试可执行文件的链接边带着用例发现(POST_BUILD 运行新产物),不进 Ninja
    # 链接池:macOS 上新链接的二进制首次执行约等 0.5 s,池深 1 会把它们排成
    # 一串(#123,见 cmake/RealmMeshNinja.cmake)。
    realmmesh_link_outside_pool(${name})
    target_link_libraries(${name} PRIVATE GTest::gtest_main ${ARG_LIBS})
    target_compile_features(${name} PRIVATE cxx_std_20)

    if(ARG_INCLUDE_DIRS)
        target_include_directories(${name} PRIVATE ${ARG_INCLUDE_DIRS})
    endif()
    if(ARG_DEFINITIONS)
        target_compile_definitions(${name} PRIVATE ${ARG_DEFINITIONS})
    endif()
    if(ARG_DEPENDS)
        add_dependencies(${name} ${ARG_DEPENDS})
    endif()

    # LABELS 不经 gtest_discover_tests 的 PROPERTIES 传:3.20 的发现脚本会把
    # 列表值拆平成多个参数。标签在其后追加的 CTest 脚本里按列表整体设置。
    if(ARG_DISCOVER_PROPERTIES)
        gtest_discover_tests(${name}
            WORKING_DIRECTORY "${REALMMESH_TEST_WORKING_DIRECTORY}"
            PROPERTIES ${ARG_DISCOVER_PROPERTIES}
        )
    else()
        gtest_discover_tests(${name}
            WORKING_DIRECTORY "${REALMMESH_TEST_WORKING_DIRECTORY}"
        )
    endif()

    # gtest 的发现结果把用例名列在 <name>_TESTS 里(TEST_LIST 缺省值);二进制
    # 尚未构建时只有占位用例 <name>_NOT_BUILT,同样挂上标签,让它在所选范围
    # 内以失败出现而不是悄悄缺席。
    set(labels ${ARG_LABELS} "target=${name}")
    set(label_script "${CMAKE_CURRENT_BINARY_DIR}/${name}_realmmesh_labels.cmake")
    file(CONFIGURE OUTPUT "${label_script}" CONTENT [=[
# Generated by realm_add_gtest: classification and target identity labels.
if(DEFINED @name@_TESTS)
  if(@name@_TESTS)
    set_tests_properties(${@name@_TESTS} PROPERTIES LABELS "@labels@")
  endif()
else()
  set_tests_properties(@name@_NOT_BUILT PROPERTIES LABELS "@labels@")
endif()
]=] @ONLY)
    set_property(DIRECTORY APPEND PROPERTY TEST_INCLUDE_FILES "${label_script}")

    if(test_class STREQUAL "unit")
        _realm_register_unit_target(${name})
    endif()
endfunction()

# Lua 测试套件的注册入口:一套件一 add_test;套件文件以 os.exit(lu.LuaUnit.run())
# 结尾,退出码 = 失败+错误数(0 即通过),正是 add_test 的成败约定。
# luaunit 单文件源码由根 CMakeLists 的 FetchContent 提供,经 LUA_PATH 注入
# require 路径(转义分号是 Lua 的「追加默认路径」语法)。
#
#   realm_add_lua_test(<name> <script 绝对路径>
#       [LABELS <label> ...]   # 缺省 unit lua:进快速子集,亦可单独 -L '^lua$' 筛选
#   )
#
# 套件的构建目标是解释器 realm_lua_cli,身份标签即 target=realm_lua_cli;
# Unit 套件把它并入聚合目标(多个套件只登记一次)。
# 用例的工作目录是调用处的二进制目录,套件里的相对路径以此为基准。
function(realm_add_lua_test name script)
    cmake_parse_arguments(PARSE_ARGV 2 ARG "" "" "LABELS")

    if(NOT ARG_LABELS)
        set(ARG_LABELS unit lua)
    endif()
    _realm_test_classification(test_class "${ARG_LABELS}")

    add_test(NAME ${name}
        COMMAND "$<TARGET_FILE:realm_lua_cli>" "${script}")
    set_tests_properties(${name} PROPERTIES
        WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}"
        ENVIRONMENT "LUA_PATH=${luaunit_SOURCE_DIR}/?.lua\;\;"
        LABELS "${ARG_LABELS};target=realm_lua_cli")

    if(test_class STREQUAL "unit")
        _realm_register_unit_target(realm_lua_cli)
    endif()
endfunction()

# 在所有测试目录之后由根 CMakeLists 调用一次:登记清单每行一个
# <Unit 构建目标>=<产物路径>,生成期求值,供 test-fast.sh 校验 --target 与
# 构建后的二进制。内容不变时不重写。
function(realmmesh_write_unit_test_registry)
    get_property(targets GLOBAL PROPERTY REALMMESH_UNIT_TARGETS)
    list(SORT targets)
    set(content "")
    foreach(target IN LISTS targets)
        string(APPEND content "${target}=$<TARGET_FILE:${target}>\n")
    endforeach()
    file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/realmmesh-unit-targets.txt"
        CONTENT "${content}")
endfunction()
