return {
    logging = {
        service_name = "gateway",
        metrics_listen_address = "127.0.0.1",
        metrics_port = 9103,
        module_levels = {
            ["framework.network"] = "info",
        },
        sample_rates = {
            malformed_request = 0.1,
        },
    },
    service_discovery = {
        instance_id = "gateway-dev-01",
        node_id = "development-node",
        zone = "development",
        advertise_address = "127.0.0.1",
    },
    tick_rate = 20,
    max_events_per_frame = 4096,
    downstream_address = "127.0.0.1",
    downstream_port = 7100,
    pipeline_fetch_capacity = 1000,
    -- 并发玩家数据查询线程数与单次拉取截止(超时按 Unavailable 计一次失败)。
    fetch_workers = 4,
    fetch_timeout_ms = 3000,
    fetch_retry_base_ms = 2000,
    fetch_retry_max = 3,
    handoff_grace_ms = 5000,
    ingress_source = {
        mode = "direct_peer",
        trusted_proxy_cidrs = {},
    },
    credential_ingress = {
        max_attach_envelope_bytes = 16384,
        max_identity_token_bytes = 2048,
        max_admission_grant_bytes = 2048,
        max_token_decoded_bytes = 3072,
        source_rate_per_second = 20,
        source_burst = 40,
        source_throttle_close_after = 3,
        session_attach_attempts = 4,
        concurrent_verifications = 128,
        max_tracked_sources = 16384,
    },
    admission = {
        identity_kid = "login-verify-v1",
        identity_issuer = "realmmesh/login-verify",
        admission_grant_issuer = "realmmesh/queue",
        deployment_id = "development",
        -- 验证键环:kid + 公钥所在的环境变量。轮换重叠期把退休 kid 一并
        -- 列在这里,直到该凭据最大寿命 + 时钟容差过去再删除;私钥永不装载。
        grant_keys = {
            {
                kid = "admission-grant-v1",
                public_key_environment = "REALMMESH_ADMISSION_GRANT_PUBLIC_KEY",
            },
        },
        -- 必须与 Queue 的签发窗口一致;协议硬上限 600s。
        grant_window_seconds = 300,
        consumption_prefix = "/realmmesh/admission/consumption",
        reservation_ttl_seconds = 10,
    },
    runtime = {
        inbound_capacity = 65536,
        outbound_capacity = 65536,
        max_commands_per_cycle = 4096,
        io_poll_interval_ms = 2,
    },
    transports = {
        {
            name = "client_quic",
            protocol = "quic",
            enabled = true,
            listen_address = "0.0.0.0",
            listen_port = 8000,
            max_sessions = 10000,
            max_payload_size = 65536,
            max_pending_output_bytes = 4194304,
            handshake_timeout_ms = 3000,
            idle_timeout_ms = 30000,
            alpn = "realmmesh-edge/1",
            certificate_chain_file_environment = "REALMMESH_TLS_CERTIFICATE_FILE",
            private_key_file_environment = "REALMMESH_TLS_PRIVATE_KEY_FILE",
        },
        {
            name = "client_tls_tcp",
            protocol = "tls_tcp",
            enabled = true,
            listen_address = "0.0.0.0",
            listen_port = 8000,
            max_sessions = 10000,
            max_payload_size = 65536,
            max_pending_output_bytes = 4194304,
            handshake_timeout_ms = 3000,
            idle_timeout_ms = 30000,
            alpn = "realmmesh-edge/1",
            certificate_chain_file_environment = "REALMMESH_TLS_CERTIFICATE_FILE",
            private_key_file_environment = "REALMMESH_TLS_PRIVATE_KEY_FILE",
        },
    },
}
