return {
    logging = {
        level = "info",
        environment = "development",
        cluster = "local",
        region = "local",
        service_name = "realm",
        file_path = ".runtime/logs/realm/realm-dev-01.jsonl",
        normal_queue_capacity = 8192,
        priority_queue_capacity = 2048,
        file_size_bytes = 134217728,
        retained_files = 8,
        console = true,
        metrics_listen_address = "127.0.0.1",
        metrics_port = 9102,
    },
    service_discovery = {
        enabled = true,
        required = false,
        endpoint = "http://127.0.0.1:2379",
        key_prefix = "/realmmesh/services",
        instance_id = "realm-dev-01",
        node_id = "development-node",
        zone = "development",
        advertise_address = "127.0.0.1",
        lease_ttl_seconds = 15,
        request_timeout_ms = 500,
        watch_interval_ms = 500,
    },
    tick_rate = 20,
    max_events_per_frame = 4096,
    downstream_address = "127.0.0.1",
    downstream_port = 8000,
    runtime = {
        inbound_capacity = 16384,
        outbound_capacity = 16384,
        max_commands_per_cycle = 4096,
        io_poll_interval_ms = 2,
    },
    transports = {
        {
            name = "realm_tls_tcp",
            protocol = "tls_tcp",
            enabled = true,
            listen_address = "0.0.0.0",
            listen_port = 7100,
            max_sessions = 10000,
            max_payload_size = 4096,
            max_pending_output_bytes = 1048576,
            handshake_timeout_ms = 3000,
            idle_timeout_ms = 30000,
            alpn = "realmmesh-edge/1",
            certificate_chain_file_environment = "REALMMESH_TLS_CERTIFICATE_FILE",
            private_key_file_environment = "REALMMESH_TLS_PRIVATE_KEY_FILE",
        },
    },
}
