include_guard(GLOBAL)

# Native targets only; libsodium's independent Make build remains uncached.
# A macro sets launcher variables in the caller before any targets are created.
macro(realmmesh_configure_ccache)
    set(REALMMESH_CCACHE AUTO CACHE STRING "Native compiler cache: AUTO, ON or OFF")
    set_property(CACHE REALMMESH_CCACHE PROPERTY STRINGS AUTO ON OFF)
    if(NOT REALMMESH_CCACHE MATCHES "^(AUTO|ON|OFF)$")
        message(FATAL_ERROR "REALMMESH_CCACHE must be AUTO, ON or OFF")
    endif()

    # Remove only launchers installed by this project, including on ON -> OFF.
    foreach(lang C CXX)
        if(DEFINED REALMMESH_MANAGED_${lang}_LAUNCHER AND
           "${CMAKE_${lang}_COMPILER_LAUNCHER}" STREQUAL "${REALMMESH_MANAGED_${lang}_LAUNCHER}")
            unset(CMAKE_${lang}_COMPILER_LAUNCHER CACHE)
            unset(CMAKE_${lang}_COMPILER_LAUNCHER)
        endif()
        unset(REALMMESH_MANAGED_${lang}_LAUNCHER CACHE)
    endforeach()

    set(realmmesh_ccache_enabled FALSE)
    set(REALMMESH_CCACHE_EXECUTABLE "" CACHE FILEPATH "Optional explicit ccache executable (empty: discover)")
    set(REALMMESH_CCACHE_RESOLVED_EXECUTABLE "" CACHE INTERNAL "Actual cache tool for observers" FORCE)
    if(NOT REALMMESH_CCACHE STREQUAL "OFF")
        # Explicit invalid paths are errors even in AUTO; only absence falls back.
        if(NOT REALMMESH_CCACHE_EXECUTABLE)
            # Do not retain an AUTO discovery across configure runs: a removed
            # tool must fall back instead of executing a stale cached path.
            unset(REALMMESH_CCACHE_DISCOVERED CACHE)
            unset(REALMMESH_CCACHE_DISCOVERED)
            find_program(REALMMESH_CCACHE_DISCOVERED NAMES ccache)
            set(REALMMESH_CCACHE_EXECUTABLE "${REALMMESH_CCACHE_DISCOVERED}")
        endif()
        if(REALMMESH_CCACHE_EXECUTABLE)
            execute_process(COMMAND "${REALMMESH_CCACHE_EXECUTABLE}" --version
                RESULT_VARIABLE realmmesh_cache_status OUTPUT_VARIABLE realmmesh_cache_version ERROR_VARIABLE realmmesh_cache_error)
            if(NOT realmmesh_cache_status EQUAL 0 OR NOT realmmesh_cache_version MATCHES "^ccache version (4\\.[0-9]+(\\.[0-9]+)?)([\r\n]|$)")
                message(FATAL_ERROR "Invalid ccache executable: ${REALMMESH_CCACHE_EXECUTABLE}: ${realmmesh_cache_error}${realmmesh_cache_version}")
            endif()
            set(realmmesh_ccache_version "${CMAKE_MATCH_1}")
            if(realmmesh_ccache_version VERSION_LESS 4.8)
                message(FATAL_ERROR "ccache >= 4.8 and < 5 required (per-invocation configuration); found ${realmmesh_ccache_version}")
            endif()
            set(realmmesh_ccache_enabled TRUE)
            set(REALMMESH_CCACHE_RESOLVED_EXECUTABLE "${REALMMESH_CCACHE_EXECUTABLE}" CACHE INTERNAL "Actual cache tool for observers" FORCE)
        elseif(REALMMESH_CCACHE STREQUAL "ON")
            message(FATAL_ERROR "REALMMESH_CCACHE=ON requires ccache >= 4.8; install ccache or choose -DREALMMESH_CCACHE=OFF")
        endif()
    endif()

    if(realmmesh_ccache_enabled)
        foreach(lang C CXX)
            if(CMAKE_${lang}_COMPILER_LAUNCHER)
                message(FATAL_ERROR "ccache conflicts with CMAKE_${lang}_COMPILER_LAUNCHER; use REALMMESH_CCACHE=OFF for a custom launcher")
            endif()
        endforeach()
        # Outside every build tree, dedicated to this checkout. Clearing a build
        # never deletes it. User presets can name another absolute directory.
        if(DEFINED REALMMESH_CCACHE_DIR AND NOT IS_ABSOLUTE "${REALMMESH_CCACHE_DIR}")
            message(FATAL_ERROR "REALMMESH_CCACHE_DIR must be an absolute path")
        endif()
        set(REALMMESH_CCACHE_DIR "${PROJECT_SOURCE_DIR}/.cache/ccache" CACHE PATH "Dedicated compiler cache directory")
        set(REALMMESH_CCACHE_MAX_SIZE "5GiB" CACHE STRING "Compiler cache size limit")
        if(NOT IS_ABSOLUTE "${REALMMESH_CCACHE_DIR}" OR REALMMESH_CCACHE_DIR MATCHES "[;\n\r]")
            message(FATAL_ERROR "REALMMESH_CCACHE_DIR must be an absolute path without list separators/newlines")
        endif()
        file(RELATIVE_PATH realmmesh_cache_relative "${CMAKE_BINARY_DIR}" "${REALMMESH_CCACHE_DIR}")
        if(NOT realmmesh_cache_relative MATCHES "^\\.\\./" AND NOT IS_ABSOLUTE "${realmmesh_cache_relative}")
            message(FATAL_ERROR "REALMMESH_CCACHE_DIR must be outside the build directory")
        endif()
        if(NOT REALMMESH_CCACHE_MAX_SIZE MATCHES "^[1-9][0-9]*(\\.[0-9]+)?(KiB|MiB|GiB|TiB|kB|MB|GB|TB)$")
            message(FATAL_ERROR "REALMMESH_CCACHE_MAX_SIZE must be a positive size with units, e.g. 5GiB")
        endif()
        # Isolate personal/system configuration. Command line settings take
        # precedence over CCACHE_* variables too: no weakened correctness keys.
        set(realmmesh_cache_config "${CMAKE_BINARY_DIR}/realmmesh-ccache.conf")
        string(REPLACE "$" "$$" realmmesh_cache_config_dir "${REALMMESH_CCACHE_DIR}")
        file(WRITE "${realmmesh_cache_config}.tmp" "# RealmMesh: native compiler cache.\ncache_dir = ${realmmesh_cache_config_dir}\nmax_size = ${REALMMESH_CCACHE_MAX_SIZE}\ncompiler_check = content\n")
        configure_file("${realmmesh_cache_config}.tmp" "${realmmesh_cache_config}" COPYONLY)
        file(REMOVE "${realmmesh_cache_config}.tmp")
        set(realmmesh_cache_launcher "${CMAKE_COMMAND};-E;env;CCACHE_CONFIGPATH=${realmmesh_cache_config};${REALMMESH_CCACHE_EXECUTABLE};cache_dir=${REALMMESH_CCACHE_DIR};max_size=${REALMMESH_CCACHE_MAX_SIZE};compiler_check=content;sloppiness=;hash_dir=true;hard_link=false;base_dir=;ignore_headers_in_manifest=;ignore_options=;compiler=;prefix_command=;prefix_command_cpp=;remote_storage=;compression=true;disable=false;depend_mode=false;direct_mode=true;read_only=false;read_only_direct=false;recache=false")
        foreach(lang C CXX)
            set(CMAKE_${lang}_COMPILER_LAUNCHER "${realmmesh_cache_launcher}" CACHE STRING "RealmMesh managed ccache launcher" FORCE)
            set(REALMMESH_MANAGED_${lang}_LAUNCHER "${realmmesh_cache_launcher}" CACHE INTERNAL "Owned native launcher" FORCE)
        endforeach()
        message(STATUS "RealmMesh ccache: ${REALMMESH_CCACHE}, ${REALMMESH_CCACHE_EXECUTABLE} ${realmmesh_ccache_version}; native C/CXX targets; dir=${REALMMESH_CCACHE_DIR}, max=${REALMMESH_CCACHE_MAX_SIZE}; libsodium excluded")
    else()
        message(STATUS "RealmMesh ccache: ${REALMMESH_CCACHE}, disabled (OFF or tool absent); native compilation uses existing custom launchers or compiler directly")
    endif()
endmacro()
